# Site settings
title: "Bill Bushey"
email: 
description: ""
baseurl: ""
url: "http://wbushey.com/"
title_description: ""
title_image: "http://www.gravatar.com/avatar/0b3f3f81b778a8825c7ead81fe706dbb?s=500&d=mm"
google_analytics: ""
disqus_account: 
github_repository: https://github.com/wbushey/wbushey.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: wbushey
github_username:  wbushey
linkedin_link: https://www.linkedin.com/in/williambushey 
google_plus_link: 
stackoverflow_link: 

# Project Names
project_names:
  body-text-extraction: Body Text Extraction
  celebrity-bar-fights: Celebrity Bar Fights
  friendly-tos: Friendly ToS
  termswatch: TermsWatch

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
